name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, github-actions-ci ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        include:
          - os: ubuntu-20.04
            TARGET: linux
          - os: windows-2019
            TARGET: windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
              
      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev liblzma-dev
        
      - name: Flutter action
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 2.1.0-10.0.pre
          channel: dev
      
      - name: Enable desktop support
        run: |
          flutter config --enable-linux-desktop --suppress-analytics
          flutter config --enable-windows-desktop --suppress-analytics

      - name: Doctor
        # Run doctor, for ease of debugging any issues.
        run: flutter doctor -v

      - name: Flutter test
        run: flutter test --suppress-analytics

      - name: Flutter build
        run: flutter build ${{ matrix.TARGET }} --suppress-analytics









